import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import Link from 'next/link';

const Home: React.FC = () => {
  return (
    <>
      <Head>
        <title>Next</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <h1>
            Find the clue!
          </h1>
          <p>
            To reach me select the <Link href="/about">route.</Link>
          </p>
          <div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
